name: Python package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=src 
        python -m xmlrunner discover -s tests -o test-reports
    - name: Upload test report
      uses:
         actions/upload-artifact@v4
      with: 
        name: test-report
        path: test-reports
  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-report
        name: Test Report
        path: '*.xml'
        reporter: java-junit

